# Generated by Django 6.0.5 on 2026-05-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_car_body_type_car_doors_car_engine_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
