# Generated by Django 6.0.5 on 2026-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_dealership_response_time_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
