# Generated by Django 6.0.5 on 2026-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dealership_facebook_url_dealership_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
