# Generated by Django 6.0.5 on 2026-06-23 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_chatusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatusage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chatusage',
            name='ip_address',
            field=models.CharField(default='unknown', max_length=45),
        ),
        migrations.AddConstraint(
            model_name='chatusage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'date'), name='unique_user_date'),
        ),
        migrations.AddConstraint(
            model_name='chatusage',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False), ('user__isnull', True)), fields=('ip_address', 'date'), name='unique_ip_date'),
        ),
    ]
