# Generated by Django 6.0.5 on 2026-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_dealershipreview_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.CharField(blank=True, choices=[('0.6', '0.6L'), ('0.7', '0.7L'), ('0.8', '0.8L'), ('0.9', '0.9L'), ('1.0', '1.0L'), ('1.1', '1.1L'), ('1.2', '1.2L'), ('1.3', '1.3L'), ('1.4', '1.4L'), ('1.5', '1.5L'), ('1.6', '1.6L'), ('1.7', '1.7L'), ('1.8', '1.8L'), ('1.9', '1.9L'), ('2.0', '2.0L'), ('2.2', '2.2L'), ('2.3', '2.3L'), ('2.4', '2.4L'), ('2.5', '2.5L'), ('2.7', '2.7L'), ('2.8', '2.8L'), ('3.0', '3.0L'), ('3.2', '3.2L'), ('3.3', '3.3L'), ('3.5', '3.5L'), ('3.6', '3.6L'), ('3.8', '3.8L'), ('4.0', '4.0L'), ('4.2', '4.2L'), ('4.4', '4.4L'), ('4.6', '4.6L'), ('4.7', '4.7L'), ('5.0', '5.0L'), ('5.2', '5.2L'), ('5.5', '5.5L'), ('5.7', '5.7L'), ('6.0', '6.0L'), ('6.2', '6.2L'), ('6.4', '6.4L'), ('6.5', '6.5L'), ('other', 'Other')], max_length=10),
        ),
    ]
