# Generated by Django 6.0.5 on 2026-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_car_engine_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_economy',
            field=models.CharField(blank=True, help_text='Fuel economy (e.g., 12 km/l, 30 mpg)', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_keys',
            field=models.IntegerField(default=1, help_text='Number of keys available'),
        ),
        migrations.AddField(
            model_name='car',
            name='value_source',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer Value'), ('dealer_measured', 'Dealer Measured Value'), ('unknown', 'Unknown')], help_text='Source of car valuation', max_length=30, null=True),
        ),
    ]
