# Generated by Django 6.0.5 on 2026-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_car_fuel_economy_car_number_of_keys_car_value_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel_economy',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_economy_combined',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('5', '5 km/L'), ('6', '6 km/L'), ('7', '7 km/L'), ('8', '8 km/L'), ('9', '9 km/L'), ('10', '10 km/L'), ('11', '11 km/L'), ('12', '12 km/L'), ('13', '13 km/L'), ('14', '14 km/L'), ('15', '15 km/L'), ('16', '16 km/L'), ('17', '17 km/L'), ('18', '18 km/L'), ('19', '19 km/L'), ('20', '20 km/L'), ('21', '21 km/L'), ('22', '22 km/L'), ('23', '23 km/L'), ('24', '24 km/L'), ('25', '25 km/L'), ('26', '26 km/L'), ('27', '27 km/L'), ('28', '28 km/L'), ('29', '29 km/L'), ('30', '30 km/L')], help_text='Combined fuel economy in km/L', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_economy_source',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer Value'), ('dealership', 'Dealership Value'), ('unknown', 'Unknown')], help_text='Source of fuel economy data', max_length=30, null=True),
        ),
    ]
