# Generated by Django 6.0.5 on 2026-07-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_car_fuel_economy_car_fuel_economy_combined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_price_negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
