# Generated by Django 6.0.5 on 2026-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_car_is_price_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='inventory_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
