from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from myapp.models import Car, Dealership
from decimal import Decimal
import random


class Command(BaseCommand):
    help = 'Create test car data for testing filters'

    def handle(self, *args, **options):
        # Create a test dealership
        dealership, created = Dealership.objects.get_or_create(
            company_name="Test Auto Solutions",
            location="Nairobi, Kenya",
            email="test@autosolutions.com",
            phone="+254-123-4567",
            is_approved=True
        )

        # Sample car data
        test_cars = [
            {
                'make': 'Toyota',
                'model': 'Prado',
                'year': 2022,
                'price': Decimal('2500000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Automatic',
                'condition': 'Excellent',
                'color': 'White',
                'seats': 7,
                'engine_size': '2.8L',
                'doors': 4,
                'body_type': 'SUV',
                'previous_owners': 1,
                'mileage': 15000,
                'dealership': dealership,
                'description': 'Excellent condition Toyota Prado, well maintained.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'BMW',
                'model': 'X6',
                'year': 2021,
                'price': Decimal('8500000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Automatic',
                'condition': 'Good',
                'color': 'Black',
                'seats': 5,
                'engine_size': '3.0L',
                'doors': 4,
                'body_type': 'SUV',
                'previous_owners': 2,
                'mileage': 45000,
                'dealership': dealership,
                'description': 'BMW X6 in good condition with full service history.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Toyota',
                'model': 'Corolla',
                'year': 2020,
                'price': Decimal('1800000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Manual',
                'condition': 'Fair',
                'color': 'Silver',
                'seats': 5,
                'engine_size': '1.8L',
                'doors': 4,
                'body_type': 'Sedan',
                'previous_owners': 3,
                'mileage': 85000,
                'dealership': dealership,
                'description': 'Toyota Corolla, reliable and economical.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Mercedes-Benz',
                'model': 'C-Class',
                'year': 2023,
                'price': Decimal('12000000.00'),
                'fuel_type': 'Diesel',
                'transmission': 'Automatic',
                'condition': 'Excellent',
                'color': 'Blue',
                'seats': 5,
                'engine_size': '2.0L',
                'doors': 4,
                'body_type': 'Sedan',
                'previous_owners': 1,
                'mileage': 8000,
                'dealership': dealership,
                'description': 'Luxury Mercedes-Benz C-Class with premium features.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Nissan',
                'model': 'Patrol',
                'year': 2019,
                'price': Decimal('3200000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Automatic',
                'condition': 'Good',
                'color': 'Gray',
                'seats': 8,
                'engine_size': '4.8L',
                'doors': 5,
                'body_type': 'SUV',
                'previous_owners': 2,
                'mileage': 120000,
                'dealership': dealership,
                'description': 'Powerful Nissan Patrol suitable for off-road adventures.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Honda',
                'model': 'CR-V',
                'year': 2022,
                'price': Decimal('2800000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Automatic',
                'condition': 'Excellent',
                'color': 'Red',
                'seats': 7,
                'engine_size': '1.5L',
                'doors': 5,
                'body_type': 'SUV',
                'previous_owners': 1,
                'mileage': 25000,
                'dealership': dealership,
                'description': 'Reliable Honda CR-V perfect for family use.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Volkswagen',
                'model': 'Golf',
                'year': 2021,
                'price': Decimal('2200000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Manual',
                'condition': 'Good',
                'color': 'White',
                'seats': 5,
                'engine_size': '1.4L',
                'doors': 3,
                'body_type': 'Hatchback',
                'previous_owners': 2,
                'mileage': 55000,
                'dealership': dealership,
                'description': 'Efficient Volkswagen Golf with great handling.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Mazda',
                'model': 'CX-5',
                'year': 2020,
                'price': Decimal('3500000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Automatic',
                'condition': 'Excellent',
                'color': 'Soul Red',
                'seats': 7,
                'engine_size': '2.5L',
                'doors': 5,
                'body_type': 'SUV',
                'previous_owners': 1,
                'mileage': 35000,
                'dealership': dealership,
                'description': 'Stylish Mazda CX-5 with advanced safety features.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Ford',
                'model': 'Ranger',
                'year': 2019,
                'price': Decimal('4200000.00'),
                'fuel_type': 'Diesel',
                'transmission': 'Manual',
                'condition': 'Fair',
                'color': 'Black',
                'seats': 5,
                'engine_size': '2.2L',
                'doors': 4,
                'body_type': 'Pickup',
                'previous_owners': 3,
                'mileage': 95000,
                'dealership': dealership,
                'description': 'Tough Ford Ranger ready for any job.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Toyota',
                'model': 'Hilux',
                'year': 2018,
                'price': Decimal('4800000.00'),
                'fuel_type': 'Diesel',
                'transmission': 'Manual',
                'condition': 'Good',
                'color': 'Dark Blue',
                'seats': 5,
                'engine_size': '2.8L',
                'doors': 4,
                'body_type': 'Pickup',
                'previous_owners': 2,
                'mileage': 150000,
                'dealership': dealership,
                'description': 'Reliable Toyota Hilux for work and play.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Subaru',
                'model': 'Forester',
                'year': 2022,
                'price': Decimal('3800000.00'),
                'fuel_type': 'Petrol',
                'transmission': 'Automatic',
                'condition': 'Excellent',
                'color': 'Green',
                'seats': 5,
                'engine_size': '2.0L',
                'doors': 5,
                'body_type': 'SUV',
                'previous_owners': 1,
                'mileage': 28000,
                'dealership': dealership,
                'description': 'All-wheel drive Subaru Forester for adventure.',
                'is_approved': True,
                'is_sold': False,
            },
            {
                'make': 'Mitsubishi',
                'model': 'Pajero',
                'year': 2020,
                'price': Decimal('4500000.00'),
                'fuel_type': 'Diesel',
                'transmission': 'Automatic',
                'condition': 'Good',
                'color': 'White',
                'seats': 7,
                'engine_size': '2.4L',
                'doors': 5,
                'body_type': 'SUV',
                'previous_owners': 2,
                'mileage': 75000,
                'dealership': dealership,
                'description': 'Capable Mitsubishi Pajero for tough terrain.',
                'is_approved': True,
                'is_sold': False,
            },
        ]

        # Create cars
        created_count = 0
        for car_data in test_cars:
            car, created = Car.objects.get_or_create(
                make=car_data['make'],
                model=car_data['model'],
                defaults=car_data
            )
            if created:
                created_count += 1
                self.stdout.write(f"Created {car_data['make']} {car_data['model']}")
            else:
                self.stdout.write(f"Updated {car_data['make']} {car_data['model']}")

        self.stdout.write(self.style.SUCCESS(f"Successfully created/updated {len(test_cars)} test cars"))
        self.stdout.write(f"New cars created: {created_count}")
        self.stdout.write("Test data ready for filter testing!")
