# Generated by Django 6.0.5 on 2026-05-25 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('pickup', 'Pickup'), ('van', 'Van'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(blank=True, choices=[(2, '2 Doors'), (3, '3 Doors'), (4, '4 Doors'), (5, '5 Doors')], null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.CharField(blank=True, choices=[('1.0', '1.0L'), ('1.2', '1.2L'), ('1.4', '1.4L'), ('1.5', '1.5L'), ('1.6', '1.6L'), ('1.8', '1.8L'), ('2.0', '2.0L'), ('2.5', '2.5L'), ('3.0', '3.0L'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='previous_owners',
            field=models.IntegerField(blank=True, choices=[(0, '0 Owners'), (1, '1 Owner'), (2, '2 Owners'), (3, '3+ Owners')], null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='submitted_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealership',
            name='area_code',
            field=models.CharField(blank=True, help_text='Area code (e.g., 00100 for Nairobi CBD)', max_length=20),
        ),
        migrations.AddField(
            model_name='dealership',
            name='business_certificate',
            field=models.FileField(blank=True, null=True, upload_to='dealership_certificates/'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealership',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealershipreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='myapp.dealership'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dealership_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('used_locally', 'Locally Used'), ('used_foreignly', 'Foreignly Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='myapp.car'),
        ),
        migrations.CreateModel(
            name='CarComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars', models.ManyToManyField(related_name='comparisons', to='myapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('buyer', 'Buyer'), ('dealership', 'Dealership')], max_length=20)),
                ('sender_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_new_car', models.BooleanField(default=True)),
                ('email_on_price_drop', models.BooleanField(default=True)),
                ('email_on_enquiry_response', models.BooleanField(default=True)),
                ('email_on_review_approved', models.BooleanField(default=True)),
                ('email_on_promotions', models.BooleanField(default=False)),
                ('sms_on_new_car', models.BooleanField(default=False)),
                ('sms_on_price_drop', models.BooleanField(default=False)),
                ('sms_on_enquiry_response', models.BooleanField(default=True)),
                ('sms_phone_number', models.CharField(blank=True, max_length=15)),
                ('push_on_new_car', models.BooleanField(default=False)),
                ('push_on_price_drop', models.BooleanField(default=False)),
                ('push_on_enquiry_response', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate_content', 'Inappropriate Content'), ('fraud', 'Fraud or Scam'), ('fake_listing', 'Fake Listing'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('duplicate', 'Duplicate Listing'), ('other', 'Other Issue')], max_length=25)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_reports', to='myapp.car')),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealership_reports', to='myapp.dealership')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this search (e.g., 'Toyota under 500k')", max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mileage_from', models.IntegerField(blank=True, null=True)),
                ('mileage_to', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(blank=True, max_length=20)),
                ('condition', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=20)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features to search for')),
                ('alert_on_new', models.BooleanField(default=True, help_text='Send alert for new matching cars')),
                ('alert_on_price_drop', models.BooleanField(default=False, help_text='Send alert when prices drop')),
                ('price_drop_percentage', models.IntegerField(default=5, help_text='Alert when price drops by this percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_alerted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly Subscription'), ('half_yearly', 'Half-Yearly Subscription'), ('yearly', 'Yearly Subscription'), ('per_car', 'Per Car Listing'), ('premium', 'Premium Dealership')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='myapp.dealership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly Subscription'), ('half_yearly', 'Half-Yearly Subscription'), ('yearly', 'Yearly Subscription'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly'), ('per_car', 'Per Car Listing')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='myapp.dealership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='myapp.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['car', 'viewed_at'], name='myapp_carvi_car_id_85fd96_idx'), models.Index(fields=['car', 'user'], name='myapp_carvi_car_id_d5cbd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DealershipClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('phone', 'Phone Number Click'), ('email', 'Email Click'), ('website', 'Website Visit'), ('directions', 'Directions Click'), ('car_view', 'Car Detail View'), ('contact', 'Contact Form Submission')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealership_clicks', to='myapp.car')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='myapp.dealership')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['dealership', 'click_type', 'clicked_at'], name='myapp_deale_dealers_081abd_idx'), models.Index(fields=['dealership', 'clicked_at'], name='myapp_deale_dealers_b4377e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='myapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'car')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_car', 'New Car Matching Search'), ('price_drop', 'Price Drop Alert'), ('enquiry_response', 'Dealership Response to Enquiry'), ('review_approved', 'Your Review Was Approved'), ('dealership_message', 'New Message from Dealership'), ('new_listing', 'New Listing from Followed Dealership'), ('promotion', 'Special Promotion')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_sent_sms', models.BooleanField(default=False)),
                ('is_sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.car')),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dealership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='myapp_notif_user_id_da55a8_idx'), models.Index(fields=['user', 'created_at'], name='myapp_notif_user_id_58c9b3_idx')],
            },
        ),
    ]
