# Generated by Django 6.0.5 on 2026-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_car_is_sold_dealership_is_approved_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
