# Generated by Django 6.0.5 on 2026-05-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_enquiry_car_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
