# Generated by Django 6.0.5 on 2026-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='variant',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
