# Generated by Django 6.0.5 on 2026-05-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('pickup', 'Pickup'), ('van', 'Van'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(blank=True, choices=[(2, '2 Doors'), (3, '3 Doors'), (4, '4 Doors'), (5, '5 Doors')], null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.CharField(blank=True, choices=[('1.0', '1.0L'), ('1.2', '1.2L'), ('1.4', '1.4L'), ('1.5', '1.5L'), ('1.6', '1.6L'), ('1.8', '1.8L'), ('2.0', '2.0L'), ('2.5', '2.5L'), ('3.0', '3.0L'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='previous_owners',
            field=models.IntegerField(blank=True, choices=[(0, '0 Owners'), (1, '1 Owner'), (2, '2 Owners'), (3, '3+ Owners')], null=True),
        ),
    ]
