# Generated by Django 6.0.5 on 2026-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='exterior_color',
            field=models.CharField(blank=True, help_text='Exterior paint color (e.g., Pearl White, Jet Black)', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(blank=True, help_text='Interior color scheme (e.g., Black, Beige, Two-Tone)', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_trim',
            field=models.CharField(blank=True, help_text='Interior trim material (e.g., Piano Black, Carbon Fiber, Wood Trim)', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='seat_material',
            field=models.CharField(blank=True, help_text='Seat material type (e.g., Leather, Cloth, Nappa Leather)', max_length=100),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='business_certificate',
            field=models.FileField(null=True, upload_to='dealership_certificates/'),
        ),
    ]
