# Generated by Django 6.0.5 on 2026-05-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_body_type_car_doors_car_engine_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='myapp.dealership'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dealership_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
