# Generated by Django 6.0.5 on 2026-05-11 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_enquiry_dealership_enquiry_dealership_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('buyer', 'Buyer'), ('dealership', 'Dealership')], max_length=20)),
                ('sender_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.enquiry')),
            ],
        ),
    ]
