# Generated by Django 6.0.5 on 2026-05-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_is_verified_emailverification_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='area_code',
            field=models.CharField(blank=True, help_text='Area code or postal code (e.g., 00100 for Nairobi CBD)', max_length=20),
        ),
        migrations.AddField(
            model_name='dealership',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code for precise location', max_length=20),
        ),
    ]
