# Generated by Django 6.0.5 on 2026-05-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_dealership_area_code_dealership_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='dealership',
            name='area_code',
            field=models.CharField(blank=True, help_text='Area code (e.g., 00100 for Nairobi CBD)', max_length=20),
        ),
    ]
