# Generated by Django 6.0.5 on 2026-06-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_car_is_top_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='myapp.car'),
        ),
    ]
