# Generated by Django 6.0.5 on 2026-05-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_report_admin_notes_remove_report_resolved_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarListingPayment',
        ),
    ]
