# Generated by Django 6.0.5 on 2026-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subscriptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly Subscription'), ('yearly', 'Yearly Subscription'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly'), ('per_car', 'Per Car Listing')], max_length=20),
        ),
    ]
