# Generated by Django 6.0.5 on 2026-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_subscriptionrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
