# Generated by Django 6.0.5 on 2026-05-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_dealership_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='myapp.dealership'),
        ),
    ]
