# Generated by Django 6.0.5 on 2026-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_car_is_premium_subscriptionrequest_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='submitted_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
