# Generated by Django 6.0.5 on 2026-05-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_car_submitted_at_car_submitted_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='business_certificate',
            field=models.FileField(blank=True, null=True, upload_to='dealership_certificates/'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly Subscription'), ('half_yearly', 'Half-Yearly Subscription'), ('yearly', 'Yearly Subscription'), ('per_car', 'Per Car Listing'), ('premium', 'Premium Dealership')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly Subscription'), ('half_yearly', 'Half-Yearly Subscription'), ('yearly', 'Yearly Subscription'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly'), ('per_car', 'Per Car Listing')], max_length=20),
        ),
    ]
