# Generated by Django 6.0.5 on 2026-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_dealership_business_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('used_locally', 'Used Locally'), ('used_foreignly', 'Used Foreignly')], max_length=20),
        ),
    ]
