# Generated by Django 6.0.5 on 2026-05-13 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_car_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='myapp.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['car', 'viewed_at'], name='myapp_carvi_car_id_85fd96_idx'), models.Index(fields=['car', 'user'], name='myapp_carvi_car_id_d5cbd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DealershipClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('phone', 'Phone Number Click'), ('email', 'Email Click'), ('website', 'Website Visit'), ('directions', 'Directions Click'), ('car_view', 'Car Detail View'), ('contact', 'Contact Form Submission')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealership_clicks', to='myapp.car')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='myapp.dealership')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['dealership', 'click_type', 'clicked_at'], name='myapp_deale_dealers_081abd_idx'), models.Index(fields=['dealership', 'clicked_at'], name='myapp_deale_dealers_b4377e_idx')],
            },
        ),
    ]
