# Generated by Django 6.0.5 on 2026-05-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_carview_dealershipclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
