# Generated by Django 6.0.5 on 2026-05-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_dealershipreview_is_approved_review_is_approved'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE myapp_review SET is_approved = 1;",
            reverse_sql="UPDATE myapp_review SET is_approved = 0;"
        ),
        migrations.RunSQL(
            "UPDATE myapp_dealershipreview SET is_approved = 1;",
            reverse_sql="UPDATE myapp_dealershipreview SET is_approved = 0;"
        ),
    ]
