# Generated by Django 6.0.5 on 2026-05-15 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_approve_existing_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars', models.ManyToManyField(related_name='comparisons', to='myapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_new_car', models.BooleanField(default=True)),
                ('email_on_price_drop', models.BooleanField(default=True)),
                ('email_on_enquiry_response', models.BooleanField(default=True)),
                ('email_on_review_approved', models.BooleanField(default=True)),
                ('email_on_promotions', models.BooleanField(default=False)),
                ('sms_on_new_car', models.BooleanField(default=False)),
                ('sms_on_price_drop', models.BooleanField(default=False)),
                ('sms_on_enquiry_response', models.BooleanField(default=True)),
                ('sms_phone_number', models.CharField(blank=True, max_length=15)),
                ('push_on_new_car', models.BooleanField(default=False)),
                ('push_on_price_drop', models.BooleanField(default=False)),
                ('push_on_enquiry_response', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this search (e.g., 'Toyota under 500k')", max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mileage_from', models.IntegerField(blank=True, null=True)),
                ('mileage_to', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(blank=True, max_length=20)),
                ('condition', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=20)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features to search for')),
                ('alert_on_new', models.BooleanField(default=True, help_text='Send alert for new matching cars')),
                ('alert_on_price_drop', models.BooleanField(default=False, help_text='Send alert when prices drop')),
                ('price_drop_percentage', models.IntegerField(default=5, help_text='Alert when price drops by this percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_alerted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_car', 'New Car Matching Search'), ('price_drop', 'Price Drop Alert'), ('enquiry_response', 'Dealership Response to Enquiry'), ('review_approved', 'Your Review Was Approved'), ('dealership_message', 'New Message from Dealership'), ('new_listing', 'New Listing from Followed Dealership'), ('promotion', 'Special Promotion')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_sent_sms', models.BooleanField(default=False)),
                ('is_sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.car')),
                ('dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dealership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='myapp_notif_user_id_da55a8_idx'), models.Index(fields=['user', 'created_at'], name='myapp_notif_user_id_58c9b3_idx')],
            },
        ),
    ]
