# Generated by Django 6.0.5 on 2026-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_carcomparison_notificationpreference_savedsearch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('used_locally', 'Locally Used'), ('used_foreignly', 'Foreignly Used')], max_length=20),
        ),
    ]
